name: CI Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [Release]
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        shell: bash

      - name: Build
        run: |
          cd build
          cmake --build . --config ${{ matrix.config }} --parallel
        shell: bash

      - name: Run executable (only on linux)
        if: runner.os == 'Linux'
        run: |
          cd build
          ./MyWorkshopProject
